# -*- coding: utf-8 -*-
"""Enem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fSIVA_rbq5vRmYXDlyCpzldJ-eqxiDT4
"""

import pandas as pd
import seaborn as sns
import statsmodels.api as sm
from statsmodels.formula.api import ols

path = 'data'

df = pd.read_csv(path + '/100k.csv')

names = pd.read_excel(path + '/names.xlsx')

df = df.sample(n=1000)

df_melt = pd.melt(df, id_vars=['media'], value_vars=['nu_idade', 'tp_sexo', 'tp_cor_raca', 'tp_st_conclusao',
                                                     'TP_ANO_CONCLUIU', 'sg_uf_esc', 'tp_dependencia_adm_esc', 'etnia',
                                                     'grupo_etario', 'regiao_pais', 'faixa_renda',
                                                     'computador', 'escolaridade_pai', 'escolaridade_mae', 'rendimento',
                                                     'pr', 'pa', 'am', 'in', 'sm_1', 'sm_2', 'sm_2_5', 'sm_5_10',
                                                     'fem', 'fed', 'est', 'mun', 'tem_comp', 'tem_internet'])

print(df_melt)

model = ols('value ~ C(media) + C(variable) + C(media):C(variable)', data=df_melt).fit()

anova_table = sm.stats.anova_lm(model, typ=2)

print(anova_table)
