# -*- coding: utf-8 -*-
"""Enem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fSIVA_rbq5vRmYXDlyCpzldJ-eqxiDT4
"""

import pandas as pd

path = 'data'

data_input = []

for i in range(2009, 2020):
    print(path + '/{}.xlsx'.format(i), 'carregando.')
    data_input.append(pd.read_excel(path + '/{}.xlsx'.format(i)))

names = pd.read_excel(path + '/names.xlsx')

print('renamed')

merged = pd.concat(data_input)

print('merged')

merged.to_csv(path + 'export_dataframe.csv', index=False, header=True)
